In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score
from time import time

In [2]:
df1 = pd.read_csv('dataset.csv')

In [5]:
len(df1)

311028

In [6]:
df1.shape

(311028, 42)

In [7]:
df1.columns= ['duration','protocol_type','service', 'flag','src_bytes',
                  'dst_bytes','Land','Wrong_fragment','urgent','hot','num_failed_logins',
                 'logged_in', 'num_compromised','root_shell','sudo_attempted', 'num_root',
                  'num_file_creations','num_shells','num_access_files','num_outbound_cmds',
                  'is_hot_login','is_guest_login','count','srv_count','serrot_rate',
                  'srv_serror_rate','rerror_rate','srv_rerror_rate','same_srv_rate',
                 'diff_srv_rate','srv_diff_host_rate','dst_host_count','dst_hostsrv_count',
                 'dst_host_same_srv_rate','dst_host_diff_srv_rate','dst_host_same_src_port_rate',
                 'dst_host_srv_diff_host_rate','dst_host_serror_rate','dst_host_srv_serror_rate',
                 'dst_host_rerror_rate','dst_host_srv_rerror_rate',
                  'Attack_names']

In [8]:
df=df1

In [9]:
df.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,Land,Wrong_fragment,urgent,hot,...,dst_hostsrv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,Attack_names
0,0,udp,private,SF,105,146,0,0,0,0,...,254,1.0,0.01,0.00,0.0,0.0,0.0,0.0,0.0,normal.
1,0,udp,private,SF,105,146,0,0,0,0,...,254,1.0,0.01,0.00,0.0,0.0,0.0,0.0,0.0,normal.
2,0,udp,private,SF,105,146,0,0,0,0,...,254,1.0,0.01,0.00,0.0,0.0,0.0,0.0,0.0,snmpgetattack.
3,0,udp,private,SF,105,146,0,0,0,0,...,254,1.0,0.01,0.01,0.0,0.0,0.0,0.0,0.0,snmpgetattack.
4,0,udp,private,SF,105,146,0,0,0,0,...,255,1.0,0.00,0.01,0.0,0.0,0.0,0.0,0.0,snmpgetattack.

In [10]:
df.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,Land,Wrong_fragment,urgent,hot,...,dst_hostsrv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,Attack_names
0,0,udp,private,SF,105,146,0,0,0,0,...,254,1.0,0.01,0.00,0.0,0.0,0.0,0.0,0.0,normal.
1,0,udp,private,SF,105,146,0,0,0,0,...,254,1.0,0.01,0.00,0.0,0.0,0.0,0.0,0.0,normal.
2,0,udp,private,SF,105,146,0,0,0,0,...,254,1.0,0.01,0.00,0.0,0.0,0.0,0.0,0.0,snmpgetattack.
3,0,udp,private,SF,105,146,0,0,0,0,...,254,1.0,0.01,0.01,0.0,0.0,0.0,0.0,0.0,snmpgetattack.
4,0,udp,private,SF,105,146,0,0,0,0,...,255,1.0,0.00,0.01,0.0,0.0,0.0,0.0,0.0,snmpgetattack.

In [11]:
labels=df1['Attack_names']
labels.head()

0           normal.
1           normal.
2    snmpgetattack.
3    snmpgetattack.
4    snmpgetattack.
Name: Attack_names, dtype: object

In [12]:
labels[labels!='normal.'] = 'attack'
labels.value_counts()

/Users/rachana/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

attack     250436
normal.     60592
Name: Attack_names, dtype: int64

In [13]:
selected_features = [
    "duration","src_bytes",
    "dst_bytes","land","wrong_fragment","urgent","hot","num_failed_logins",
    "logged_in","num_compromised","root_shell","su_attempted","num_root",
    "num_file_creations","num_shells","num_access_files","num_outbound_cmds",
    "is_host_login","is_guest_login","count","srv_count","serror_rate",
    "srv_serror_rate","rerror_rate","srv_rerror_rate","same_srv_rate",
    "diff_srv_rate","srv_diff_host_rate","dst_host_count","dst_host_srv_count",
    "dst_host_same_srv_rate","dst_host_diff_srv_rate","dst_host_same_src_port_rate",
    "dst_host_srv_diff_host_rate","dst_host_serror_rate","dst_host_srv_serror_rate",
    "dst_host_rerror_rate","dst_host_srv_rerror_rate"
]

In [14]:
len(selected_features)

38

In [15]:
df=df.drop(['protocol_type','service','flag','Attack_names'],axis=1)

In [16]:
df.shape

(311028, 38)

In [17]:
df.describe()

,duration,src_bytes,dst_bytes,Land,Wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,dst_host_count,dst_hostsrv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate
count,311028.000000,3.110280e+05,3.110280e+05,311028.000000,311028.000000,311028.000000,311028.000000,311028.000000,311028.000000,311028.000000,...,311028.000000,311028.000000,311028.000000,311028.000000,311028.000000,311028.000000,311028.000000,311028.000000,311028.000000,311028.000000
mean,17.902793,1.731707e+03,7.479956e+02,0.000029,0.000762,0.000051,0.014677,0.002363,0.172476,0.011243,...,235.282618,199.193738,0.793494,0.024953,0.547920,0.004566,0.058764,0.058791,0.142659,0.141694
std,407.645054,1.276569e+05,1.612021e+04,0.005379,0.040367,0.009821,0.312069,0.049990,0.377795,1.958328,...,60.913386,100.306584,0.387090,0.096003,0.491963,0.035773,0.231296,0.232997,0.344380,0.346574
min,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,1.050000e+02,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,255.000000,244.000000,0.970000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,5.200000e+02,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,255.000000,255.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,1.032000e+03,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,255.000000,255.000000,1.000000,0.010000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,57715.000000,6.282565e+07,5.203179e+06,1.000000,3.000000,3.000000,101.000000,4.000000,1.000000,796.000000,...,255.000000,255.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [18]:
#df=df.astype(float)
#df.apply(lambda x: MinMaxScaler().fit_transform(x))
#df.describe()

In [19]:
 X_train, X_test,y_train,y_test = train_test_split(df,labels, test_size=0.1,random_state=42)

In [20]:
#Training using KNN (Supervised Learning)
knn = KNeighborsClassifier(n_neighbors = 5, algorithm = 'ball_tree', leaf_size=500)
t0 = time()
knn.fit(X_train,y_train)
tt = time()-t0
print("Classifier trained in {} seconds".format(round(tt,3)))

Classifier trained in 38.163 seconds

In [21]:
#Prediction using KNN
t0 = time()
pred = knn.predict(X_test)
tt = time() - t0
print("Predicted in {} seconds".format(round(tt,3)))

Predicted in 229.32 seconds

In [22]:
#Calculating accuracy of KNN

acc = accuracy_score(pred, y_test)
print("Accuracy of KNN is {}.".format(round(acc,4)))

Accuracy of KNN is 0.9789.

In [23]:
#Unsupervised learning (K means clustering)

from sklearn.cluster import KMeans
k = 30
km = KMeans(n_clusters = k)

In [24]:
#Training into clusters using k-means 
t0 = time()
km.fit(X_test)
tt = time()-t0
print("Clustered in {} seconds".format(round(tt,3)))

Clustered in 1.356 seconds

In [25]:
#checking the cluster sizes
pd.Series(km.labels_).value_counts()

16    10730
19     7619
0      5559
28     3440
15     1261
13      611
18      582
25      387
7       252
17      158
8       103
6        75
1        61
29       56
27       45
26       39
20       32
23       30
4        26
14       13
10        9
5         3
9         3
11        2
12        2
2         1
3         1
21        1
22        1
24        1
dtype: int64

In [26]:
label = df1['Attack_names']
label_names = list(map(
    lambda x: pd.Series([label[i] for i in range(len(km.labels_)) if km.labels_[i]==x]), 
    range(k)))

In [27]:
#Print labels for each cluster.
for i in range(k):
    print("Cluster {} labels:".format(i))
    print(label_names[i].value_counts())
    print()

Cluster 0 labels:
attack     5341
normal.     218
dtype: int64

Cluster 1 labels:
attack     59
normal.     2
dtype: int64

Cluster 2 labels:
attack    1
dtype: int64

Cluster 3 labels:
attack    1
dtype: int64

Cluster 4 labels:
attack     25
normal.     1
dtype: int64

Cluster 5 labels:
attack    3
dtype: int64

Cluster 6 labels:
attack     69
normal.     6
dtype: int64

Cluster 7 labels:
attack     243
normal.      9
dtype: int64

Cluster 8 labels:
attack     100
normal.      3
dtype: int64

Cluster 9 labels:
attack    3
dtype: int64

Cluster 10 labels:
attack     8
normal.    1
dtype: int64

Cluster 11 labels:
attack    2
dtype: int64

Cluster 12 labels:
attack    2
dtype: int64

Cluster 13 labels:
attack     585
normal.     26
dtype: int64

Cluster 14 labels:
attack     12
normal.     1
dtype: int64

Cluster 15 labels:
attack     1215
normal.      46
dtype: int64

Cluster 16 labels:
attack     10298
normal.      432
dtype: int64

Cluster 17 labels:
attack     152
normal.      6
dtype: int64

Cluster 18 labels:
attack     560
normal.     22
dtype: int64

Cluster 19 labels:
attack     7338
normal.     281
dtype: int64

Cluster 20 labels:
attack     31
normal.     1
dtype: int64

Cluster 21 labels:
attack    1
dtype: int64

Cluster 22 labels:
attack    1
dtype: int64

Cluster 23 labels:
attack     26
normal.     4
dtype: int64

Cluster 24 labels:
attack    1
dtype: int64

Cluster 25 labels:
attack     374
normal.     13
dtype: int64

Cluster 26 labels:
attack    39
dtype: int64

Cluster 27 labels:
attack    45
dtype: int64

Cluster 28 labels:
attack     3308
normal.     132
dtype: int64

Cluster 29 labels:
attack     52
normal.     4
dtype: int64

In [28]:
#Predicting using k-means for test data
t0 = time()
pred = km.predict(X_test)
tt = time() - t0
print("Assigned clusters in {} seconds".format(round(tt,3)))

Assigned clusters in 0.014 seconds

In [29]:
print(km.labels_)

[19 28 19 ... 16  0  0]